### ISSUE TITLE
OutOfMemoryError when loading image stops images from cycling

### ISSUE THREAD

**Issue by ikromin** [ikromin/jphotoframe#1]
When an OutOfMemoryError is thrown during loading of a new photo, no other photos are loaded any more.

Below is the stack trace.

Exception in thread "Thread-3" java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:92)
    at java.awt.image.ComponentSampleModel.createDataBuffer(ComponentSampleModel.java:415)
    at java.awt.image.Raster.createWritableRaster(Raster.java:941)
    at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1073)
    at javax.imageio.ImageReader.getDestination(ImageReader.java:2896)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1066)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1034)
    at javax.imageio.ImageIO.read(ImageIO.java:1448)
    at javax.imageio.ImageIO.read(ImageIO.java:1308)
    at net.igorkromin.View.displayImage(View.java:230)
    at net.igorkromin.Controller.updatePhoto(Controller.java:156)
    at net.igorkromin.Controller.access$000(Controller.java:38)
    at net.igorkromin.Controller$1.run(Controller.java:64)

**Comment by ikromin** [comment]
Fixed in 0.3
